### ISSUE TITLE
Cosas que faltan

### ISSUE THREAD

**Issue by Gon-Analista** [papusprox10jpg/eva.formativa4#13]
- [ ]  Crear archivo de funciones 7u7

- [ ]  Validar todo u3u

- [x]  Terminar el dibujo del avión

- [x]  Terminar opción 1 del menú

- [ ]  Terminar opción 2 del menú

- [ ]  Terminar opción 3 del menú

- [ ]  Terminar opción 4 del menú

- [ ]  Buscar errores con Testers

- [ ]  Terminar el programa xD

- [ ]  Crear el video :C

**Comment by Wolfmatee** [comment]
vamoh bien :)

**Comment by Gab-Serrano** [comment]
Subí documento que resume lo del instructivo, para que chequeen qué está listo
